version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    # image: kirillbogomolov7ric/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      # - media:/var/www/kittygram/media/
      # - media:/backend_media
      # - media:/app/backend/media
      - media:/media
      # - media:/media/cats/images/
    depends_on:
      - db
  
  frontend:
    build: ./frontend/
    # image: kirillbogomolov7ric/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  
  gateway:
    build: ./nginx/
    # image: kirillbogomolov7ric/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      # - media:/media
      - media:/media/cats/images/
      # - media:/backend_media
      # - media:/var/www/kittygram/media/
    depends_on:
      - backend
